name: Deployment pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  NON_SKIP_PR: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    outputs:
      is_deployed: ${{ steps.deploy.outcome == 'success'}} 

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - run: npm install
      - run: npm run lint
      - run: npm run build

      - name: Deploy to Render
        if: ${{ env.NON_SKIP_PR == 'true' }}
        id: deploy
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run:  |
          curl "$deploy_url"
      
      - name: Discord success notification
        uses: tsickert/discord-webhook@b217a69502f52803de774ded2b1ab7c282e99645
        if: ${{ success() && env.NON_SKIP_PR == 'true' }}
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: 'Deployment Bot'
          embed-title: 'A new version of redux-anecdotes deployed'
          embed-description: 'to ${{ secrets.RENDER_URL }} by ${{ github.actor }}'

      - name: Discord failure notification
        uses: tsickert/discord-webhook@b217a69502f52803de774ded2b1ab7c282e99645
        if: ${{ failure() && env.NON_SKIP_PR == 'true' }}
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: 'Deployment Bot'
          embed-title: 'Deployment failed'
          embed-description: 'commit ${{ github.event.head_commit.url }} by ${{ github.event.head_commit.author.username }} broke the build'

  tag_release:
    needs: [simple_deployment_pipeline]
    if: |
      ${{ needs.simple_deployment_pipeline.outputs.is_deployed == 'true' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch          